# Generated by Django 5.0.4 on 2024-04-25 23:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('missions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Beneficiary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='mission',
            name='beneficiary',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='missions.beneficiary'),
            preserve_default=False,
        ),
    ]
